on: [push]

jobs:
  Sample-Run-of-Jekyll-Deploy-Test-Action:
    runs-on: ubuntu-latest
    name: This job tests the functionality of the Jekyll Deploy Test Action.
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Jekyll Deploy Test
      uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v1
      with:
        gemfile-location: '/sample-jekyll-website'
        site-directory: '/sample-jekyll-website'
